### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../data/pickles/where2go_model.pkl'

### ISSUE THREAD

**Issue by rbhatia46** [da248/where2go#1]
When I run the web app in a python2.7 environment with all the dependencies, I get the following error:

```
Traceback (most recent call last):
  File "app.py", line 44, in <module>
    app.where2go = load_pickle()
  File "app.py", line 19, in load_pickle
    return pkl.load(open('../data/pickles/where2go_model.pkl', 'rb'))
IOError: [Errno 2] No such file or directory: '../data/pickles/where2go_model.pkl'
```

Can you please provide the required pkl file

**Comment by laugoon** [comment]
I also get this error, and I find :
"with open('../../data/pickles/where2go_model.pkl', 'wb') as f:
cPickle.dump(where2go, f) "
in "code/model/where2go_model.py"
I guess this file can be created.
